### ISSUE TITLE
Warnings / Errors sporadically not updating

### ISSUE THREAD

**Issue by lzkelley** [steelbrain/linter#1002]
Often (but sporadically) certain warnings and errors aren't updated to reflect that they are no longer present.  For example, using linter-flake8 (for python) *`F841 - local variable '<VARNAME>` is assigned to but never used`*, will remain even after that variable *is definitely* being used.  

Work-arounds:
-   Closing the open window/buffer and reopening it fixes the problem.
-   Cutting and pasting the line causing the error *sometimes* seems to force a re-check, and fixes the problem.

It seems like there is some underlying bug the warnings/errors not to be updated, or for previous warnings not to be erased.

**Comment by Arcanemagus** [comment]
I've noticed this with a few different `linter-*` providers, messages simply not being removed from display when they are no longer present in the return of the linter. I've never been able to get a good way to reproduce it though.

**Comment by steelbrain** [comment]
If I had to guess, it's an error in the provider

**Comment by Arcanemagus** [comment]
Next time I see it I'll double check, but I'm pretty sure the provider is _not_ sending the messages on in its return.

**Comment by laurelnaiad** [comment]
This is happening almost constantly right now with the Javascript linter.

**Comment by steelbrain** [comment]
Here's something from my experience, some of the javascript linters specify a range that starts and ends at the same position, in those cases you will not see anything underlined at all, but if you click that error in the bottom panel it'll show a bubble and the error would even go away if you fix it. so nothing's broken, it's just a provider range issue

**Comment by jeffschwartz** [comment]
Running Mac OSX v10.9.5,  Atom 1.2.4, linter 1.11.2, linter-jshint 1.2.1 and I have Lint As You Type selected but it is not linting as I type. I have to save the file first in order to initiate linting.

**Comment by emileber** [comment]
I'm having this exact bug, I updated Atom to 1.8.0 on windows and the bug is still present (sporadically).

Windows 10 Pro 64 bits

```
Community Packages (22) C:\Users\emile.bergeron.CAMINO\.atom\packages
├── atom-beautify@0.29.8
├── atom-terminal@0.8.0
├── autoclose-html@0.23.0
├── color-picker@2.1.1
├── docblockr@0.7.3
├── emmet@2.4.3
├── file-icons@1.7.14
├── foldername-tabs@0.1.11
├── git-plus@5.15.0
├── highlight-selected@0.11.2
├── linter@1.11.8
├── linter-jshint@2.1.0
├── linter-php@1.2.0
├── merge-conflicts@1.4.4
├── minimap@4.24.4
├── minimap-highlight-selected@4.4.0
├── open-recent@5.0.0
├── pigments@0.29.2
├── sass-compiler-autosave@0.5.0
├── split-diff@1.0.2
├── temporary-root@1.0.0
└── todo-show@1.6.0
```

The status bar widget indicates 0 errors/warnings but the little message popup never leaves, I must close the tab and reopen it. Deleting the line and undoing the deletion works as well in fixing the bug temporarily.

**Comment by steelbrain** [comment]
@emileber I just tried and am unable to repro this. Can you share a gif or something?

**Comment by emileber** [comment]
![linter-jshint](https://cloud.githubusercontent.com/assets/3286135/16021243/8ed74958-317f-11e6-9ff1-e98eb06e1d44.gif)

This is just one case I could reproduce easily. It also happens a lot with missing semicolon, which is a pain since it's almost every line.

**Comment by emileber** [comment]
The problem appeared in 1.11.7, I just tested 1.11.4 and 1.11.6 and they are ok.

**Comment by steelbrain** [comment]
@emileber You can expect a fix real soon

**Comment by steelbrain** [comment]
@emileber Fixed by v1.11.9

**Comment by emileber** [comment]
Well, that was quick! Many thanks

**Comment by lzkelley** [comment]
1.9.0-beta0
linter: 1.11.10
linter-flake8: 1.13.2

![linter-err](https://cloud.githubusercontent.com/assets/3839265/16047752/6b51bd74-321f-11e6-91a3-59325e39db21.gif)

**Comment by steelbrain** [comment]
@lzkelley There seem to be many weird issues in tooltips part, I'll be fixing them all at once with linter@2.0

**Comment by lzkelley** [comment]
@steelbrain is this only an issue with the tooltips?  It the case above, there shouldn't be an error indicated at all.  It seems like it's the linter not re-linting properly

**Comment by lzkelley** [comment]
Another example of this not being a purely tooltips related issue:

![linter-err_2](https://cloud.githubusercontent.com/assets/3839265/16092429/de49df8c-3305-11e6-8dfc-62c6f350adec.gif)

@emileber have your issues gone away with 1.11.9?

**Comment by emileber** [comment]
@lzkelley my issues were resolved in 1.11.10 (as 1.11.9 had a typo, see https://github.com/steelbrain/linter/issues/1182)

**Comment by steelbrain** [comment]
Fixed by #1185

**Comment by lzkelley** [comment]
Thanks @steelbrain, the linter *definitely* seems to be behaving *noticeably* better!
.... But still having the same issue at times ...

1.9.0-beta0
Linter 1.11.11
Linter-flake8 1.13.2

![linter-err_3](https://cloud.githubusercontent.com/assets/3839265/16158533/8c1edc1c-348b-11e6-996d-ffc074a75249.gif)

**Comment by emileber** [comment]
@lzkelley As I'm having no issue since 1.11.11, could it be a problem related to linter-flake8?

**Comment by lzkelley** [comment]
@emileber I have no idea...  Do you (or anyone) have any suggestions for how to figure that out?

**Comment by Arcanemagus** [comment]
Anything related to the display of messages, or running of the linter providers would be here in linter, not in one of the providers.

**Comment by steelbrain** [comment]
@lzkelley Thanks for the gif, if I understand the bug pointed out correctly, I think I've already fixed it in the rewrite UI branch. I am sorry it's taking too much, I am not good at css :(

Anyways, the fix is to observe the marker and update the message object with the latest range after each update, then recalculate the key for the message and garbage collect it. I'll try to backport the fixes soon

**Comment by lzkelley** [comment]
Dude, no apologies @steelbrain !  Thanks so much for working on this!  I really wish I understood atom's workings, or coffee/java-script... so that I could help directly.  Hopefully some day!

**Comment by steelbrain** [comment]
Hey guys, can you try v1.11.12 to see if it fixes this for you?

**Comment by lzkelley** [comment]
It seemed like things were behaving much better (maybe they still are?), but - I'm sorry to say - there are still some bugs:

![linter-err_4](https://cloud.githubusercontent.com/assets/3839265/16315279/96d9aec0-394f-11e6-8b5c-2d34f1bc05e2.gif)

So far, at least, I haven't seen a case where the colored dot and dashed underline persist after fixing an error.  But as the above gif shows, the popup is still appearing --- and now it's not going away after replacing the line, oddly enough.

**Comment by steelbrain** [comment]
Well it seem that unfortunately, you'll have to wait for the next major release :(

**Comment by lzkelley** [comment]
Some of the issues seem to be associated with having split panes.  For example, sometimes only a single pane of the same file will have problems, but I just had an instance of closing a file in the right-pane, fixing the issues (many locations incorrectly marked as warnings/errors) in the left-pane.  I don't know if that might mean something more significantly for finding/determining the underlying problem...
