### ISSUE TITLE
Clicking Top Of Errors Panel Changes Cursor

### ISSUE THREAD

**Issue by eviljoe** [steelbrain/linter#1102]
Single-clicking the top of the linter errors/warnings panel (instead of clicking & dragging) will change the cursor into a "ns-resize."  When the cursor in this state, it will be a "ns-resize" in places where you would normally see the normal arrow cursor ("default").

**To Recreate:**
 * Create one or more linter errors/warnings
 * Single-left-click the top of the linter errors/warning panel.  I am pretty sure this is the `linter-panel` element.
 * The cursor will change to a "ns-resize" cursor

**Weak Attempt At Showing The Problem Areas:**
![ns-cursor](https://cloud.githubusercontent.com/assets/7276751/13919526/5531eaaa-ef44-11e5-9f2c-07a5b2f6ef36.png)

**Comment by steelbrain** [comment]
I can't really confirm this bug, but it has been fixed in `linter-ui-default`. I'll keep this open until it's released though

**Comment by eviljoe** [comment]
Awesome.  Thanks!

**Comment by eviljoe** [comment]
I am still having this issue, and I found a way to recreate it more easily.  Single-click the top-half of the first linter link.  This is a "hot" area for the gripper that resizes the error messages panel.  This adds `style="cursor: ns-resize"` to Atom's root HTML element.

To remove the "ns-resize" style, you can click-and-drag the top half of the first linter link.

![ns-resize](https://cloud.githubusercontent.com/assets/7276751/16813960/d6bb1102-4901-11e6-9c51-58dcceab416b.png)

**Comment by steelbrain** [comment]
Ahhh, it's actually a feature, you can click hold and drag to resize the cursor

**Comment by steelbrain** [comment]
Closing based on above discussion

**Comment by cnyarx** [comment]
I think the resize event should not be fired if user click the first link text.
Is it possible to disable the resize event while clicking the link text?
