### ISSUE TITLE
feature request: only show linter in atom tray when a supported file type is open

### ISSUE THREAD

**Issue by andy-esch** [steelbrain/linter#1283]
The behavior I'm seeing in my installation is that the linter check always shows in the system tray despite the type of file I'm currently looking at (markdown, sql, etc. etc.). To reduce visualize noise, though, it'd be awful nice to have an option to only show the linter status if the currently viewed file is a type that the linter looks at. Better yet, having the option to specify the files that the linter doesn't look at would allow the user to have the flexibility they'd need.

**Comment by steelbrain** [comment]
In a perfect world, you would also install linter providers for markdown and sql as well :)
Any reasons why you wouldn't/haven't?

**Comment by Arcanemagus** [comment]
Just a note: There actually isn't a linter for SQL (that I know of) 😛.

**Comment by ohasselblad** [comment]
@steelbrain good point about living in a linter-perfect world :) I guess better example files are .txt, .csv, .sql, and so on.

**Comment by shanept** [comment]
+1 for this one.
I have a linter for JavaScript and I don't want it showing up when I'm working on my PHP code as I have a separate linter for that.

**Comment by steelbrain** [comment]
@shanept Your usecase is actually different, it was a File vs Project tab thingy. Anyway, it's all been fixed in v2, no more confusion! :)

As for @andy-esch, thank you for your suggestion but we cannot support it :)

**Comment by shanept** [comment]
Hi steelbrain,

I've upgraded to v2 and it all looks really awesome so far, so kudos for the epic work!
However I am still having this issue. I'm not sure what you mean by it's a "File vs Project" thing?

I am using the "linter-jscs" package for which this package is a dependency. For my JavaScript, it is great. However I do a lot of PHP work and use a command-line utility for the linting of my PHP code, and it would be great if I could stop the linter showing for PHP files.

I have had a look at the settings and have noticed the option to "Ignore files matching this Glob", and have modified it to this value: `**/*.min.{js,css},*.php` - however it does not ignore my PHP when I do this. I have also tried `**/*.min.{js,css},**/*.php` to no avail.

Am I on the right track here?

Thanks again, loving the work!

**Comment by steelbrain** [comment]
@shanept Sorry I misunderstood your issue,

Your problem could have two possible scenarios

1. You have two tabs open (php and js) and you were seeing both of them in either file
2. You were seeing the JS errors INSIDE of Php.

The error you described is 2 (previously I thought it was 1). Can you please open a new issue as it's unrelated to this one? Also in your new issue, make sure to select the line in the php file where you see the jscs error and invoke `linter:debug` command from the command pallete and then include it's contents or screenshot. Thank You!

**Comment by shanept** [comment]
Thanks for the quick reply. It's not quite like either of those issues either...
What I am talking about is the little [0|0|0] at the bottom of the screen. In the last version it was a lot larger and more distracting, the new one is a lot better in that regard. It isn't finding JavaScript errors in my PHP - in fact I disabled the linter-jscs package then restarted and it isn't affecting this in any way.

What I have found with the debug output is that when I start the editor up fresh, the "All Linter providers" line is empty, as is the "Matching Linter providers" line.
I then open a javascript file and close it, to go back to my PHP file, to see that the JSCS provider has been loaded however is not matching the PHP file.
If I then go back to the JS file, I can see that it matches the JSCS file.

Does this make sense?
So I suppose you could say that what I am imagining is that the bottom 3 indicators for errors will not display unless a matching linter is found for the currently displayed document.
Does this make more sense? Sorry for the confusion so far.

I can certainly open a new issue but I feel that it's technically related to the original issue here?

**Comment by Arcanemagus** [comment]
`linter-jscs` is _only_ for linting JavaScript files, it sounds like you are asking for it to lint JS inside the PHP file, which isn't something it can do.

I would _highly_ recommend you move over to using ESLint, all development on JSCS has stopped as the team merged into ESLint. One of the advantages of moving over to that is there is a plugin (`eslint-plugin-html`) that can extract the JS from the HTML (PHP) and lint it.

**Comment by shanept** [comment]
@Arcanemagus I'm not trying to get JSCS to lint my PHP code, and my PHP code has no JS inside it.

I am trying to get this thing to stop showing up for my PHP files, as I don't have a linter installed for PHP. I am trying to achieve the exact same thing as andy-esch was trying to achieve. Is it possible to stop the linter from displaying the below screenshot on *.php files, through the "Ignore files matching this Glob" setting this plugin has?
![screenshot from 2017-03-14 12-44-06](https://cloud.githubusercontent.com/assets/5936269/23886281/bc598fe6-08b4-11e7-8cb5-447f05a1732b.png)
