### ISSUE TITLE
Clicking line number clears linter warnings, does not go to line and begins odd behaviour

### ISSUE THREAD

**Issue by hughlaw** [steelbrain/linter#1467]
When clicking the line number for a reported linter warning, I am not being taken to the line in the file. Instead, the linter warnings panel is cleared of all warnings.
Upon closing and reopening the linter panel, instead of it showing, a new tab is created named `linter-ui-default` which seems to be an empty file.

Atom Version: 1.17.0 Mac
Dev tools reporting the following errors as soon as page is loaded (3 times):
```
Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
/Users/hughlaw/.atom/packages/linter-ui-default/lib/panel/index.js:91
```
then once I try and reopen the linter panel I get the same error except instead of 'hide' it's 'show' on line 74.

![strange-linter-behaviour](https://cloud.githubusercontent.com/assets/3457716/26145483/7130d51c-3ae4-11e7-856d-dd68e747e82b.gif)
![screen shot 2017-05-17 at 09 37 10](https://cloud.githubusercontent.com/assets/3457716/26145490/7586f6be-3ae4-11e7-9285-e8ff1ce87370.png)

**Comment by steelbrain** [comment]
Will investigate

**Comment by cenkentimist** [comment]
This is happening to me for errors as well.

**Comment by vwarner1411** [comment]
Happening for me as well. If I click in the linter panel, basically the whole linter UI vanishes.


Before:
<img width="1680" alt="before click" title="before click" src="https://cloud.githubusercontent.com/assets/4649997/26163053/aded2efa-3ae5-11e7-9a45-a4e4a2588660.png">

After:
<img width="1680" alt="after click" title="after click" src="https://cloud.githubusercontent.com/assets/4649997/26163052/adec6574-3ae5-11e7-836c-83f4e635fd72.png">

**Comment by lydianchord** [comment]
I'm getting the same problem in Atom 1.17.0 for Windows

**Comment by steelbrain** [comment]
Should be fixed on the latest version of linter-ui-default

**Comment by hughlaw** [comment]
@steelbrain Thanks for your quick work on this.
Upgraded linter-ui-default to 1.5.2 - I'm afraid the issue still seems to be present :(
Let me know of you want me to try anything else in my tests...

![strange-linter-behaviour-2](https://cloud.githubusercontent.com/assets/3457716/26167907/256a3f96-3b30-11e7-84fe-91741d462feb.gif)

**Comment by vwarner1411** [comment]
I am still experiencing this after updating to 1.5.2 and restarting Atom. 

I am also seeing (which might be a separate bug, but could be related) that the linter wont show information for other files, only the first file linted. The information doesnt display on the other files, but the error/warning count in the bottom left does show information for the first file.

See here, the count on the bottom left shows errors for DASWidget.js, even though I am in testWS.js. If I open DASWidget.js, it shows all the lines and debug info, but that is the only file that linting works on.
<img width="1680" alt="screen shot 2017-05-17 at 11 48 07 am" src="https://cloud.githubusercontent.com/assets/4649997/26168266/baf7fcea-3af6-11e7-87bf-c19fd0a28199.png">

 I can certainly open a new bug if we think this is not related, or just for tracking.

**Comment by steelbrain** [comment]
There's actually a number of things in play here

### Seeing count in bottom and not in Panel

Linter UI's default settings were changed in the most recent release and the status bar's default scope was made "Entire Project" while Linter panel still represents only current file, you can change these configs for `linter-ui-default` in settings view

### Linter panel not showing once hidden requiring manual unhiding

This is because you have selected linter to hide when panel is empty

<img src="https://cloud.githubusercontent.com/assets/4278113/26168602/1b84db52-3b54-11e7-9c61-51fb5cadafcb.png">

This is enabled by default to some-what match the old behavior. You can disable it if you want and it'll stick regardless of if you have errors or not

---

The original bug has been fixed, these are just new behaviors. The status bar one was adopted because users in default config had no way of knowing other than tree view if another file had any errors.

**Comment by vwarner1411** [comment]
I actually unchecked that when this issue first started. I have had that option unchecked currently, and the issue still persists. Everytime I click, I have to manually unhide.

<img width="1680" alt="screen shot 2017-05-17 at 12 00 12 pm" src="https://cloud.githubusercontent.com/assets/4649997/26168743/6ba6e014-3af8-11e7-933a-57786501ee9b.png">

**Comment by lydianchord** [comment]
After upgrading, I'm also still getting the originally reported issue where clicking within the linter panel makes the whole panel blank and doesn't move the cursor to the line in question.

**Comment by vwarner1411** [comment]
Yeah, I dont think the original bug here has been fixed. The console error included with the original issue is no longer there, however the actual issue reported (clicking a line, and having the linter hide) is still happening.

**Comment by steelbrain** [comment]
v1.5.4 is out people. Docks have been a mess, thanks for being patient

**Comment by cenkentimist** [comment]
It seems to work again now :)
